language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
    - cd sources
    - composer install

script:
    - phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)